#!/bin/sh
set -e

KEYCLOAK_URL="${NEXT_PUBLIC_KEYCLOAK_URL:-}"
KEYCLOAK_REALM="${NEXT_PUBLIC_KEYCLOAK_REALM:-}"
KEYCLOAK_CLIENT_ID="${NEXT_PUBLIC_KEYCLOAK_CLIENT_ID:-}"
TENANCY_BASE_DOMAIN="${NEXT_PUBLIC_TENANCY_BASE_DOMAIN:-}"
API_URL="${NEXT_PUBLIC_API_URL:-}"
APP_VERSION="${NEXT_PUBLIC_APP_VERSION:-}"

cat > /app/public/env.js <<EOF
window.__ENV__ = {
  NEXT_PUBLIC_KEYCLOAK_URL: "${KEYCLOAK_URL}",
  NEXT_PUBLIC_KEYCLOAK_REALM: "${KEYCLOAK_REALM}",
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}",
  NEXT_PUBLIC_TENANCY_BASE_DOMAIN: "${TENANCY_BASE_DOMAIN}",
  NEXT_PUBLIC_API_URL: "${API_URL}",
  NEXT_PUBLIC_APP_VERSION: "${APP_VERSION}"
};
EOF

exec "$@"
