#!/bin/sh
set -e

KEYCLOAK_URL="${NEXT_PUBLIC_KEYCLOAK_URL:-}"
KEYCLOAK_REALM="${NEXT_PUBLIC_KEYCLOAK_REALM:-}"
KEYCLOAK_CLIENT_ID="${NEXT_PUBLIC_KEYCLOAK_CLIENT_ID:-}"
API_URL="${NEXT_PUBLIC_API_URL:-}"

cat > /app/public/env.js <<EOF
window.__ENV__ = {
  NEXT_PUBLIC_KEYCLOAK_URL: "${KEYCLOAK_URL}",
  NEXT_PUBLIC_KEYCLOAK_REALM: "${KEYCLOAK_REALM}",
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}",
  NEXT_PUBLIC_API_URL: "${API_URL}"
};
EOF

exec "$@"
